// Regenerates `src/lib/bible/languageData.generated.ts`.
//
//   node scripts/languages.mjs
//
// The upstream API reports its own book names and translation list on every
// chapter response, so the catalogue for a language is one fetch. Scripture
// metadata does not change, so the output is committed and nothing at build or
// run time depends on holybible.ge being up.
//
// Georgian, English and Russian are not here: their arrays were hand-checked
// against the old app and live in `languages.ts` itself.

import { writeFile } from 'node:fs/promises';

const UPSTREAM = 'https://holybible.ge/service.php';

/** The API's own language codes, minus the three we keep by hand. */
const CODES = ['es', 'fr', 'gr', 'he', 'ae', 'tr', 'la', 'jp', 'ua', 'ab', 'os'];

const fetchLanguage = async code => {
  const query = new URLSearchParams({ w: '4', t: '1', m: '', s: '', mv: '', language: code, page: '1' });
  const response = await fetch(`${UPSTREAM}?${query}`);

  if (!response.ok) throw new Error(`${code}: upstream ${response.status}`);

  const body = await response.json();

  if (!body.bibleNames?.length) throw new Error(`${code}: no book names`);
  if (!body.versions?.length) throw new Error(`${code}: no translations`);

  // Some names arrive with non-breaking spaces around them.
  return {
    names: body.bibleNames.map(name => String(name).replace(/ /g, ' ').trim()),
    versions: body.versions.map(version => String(version).trim()),
  };
};

const quote = value => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const list = values => `[${values.map(quote).join(', ')}]`;

const loaded = Object.fromEntries(
  await Promise.all(CODES.map(async code => [code, await fetchLanguage(code)])),
);

const file = `// Generated by scripts/languages.mjs — do not edit by hand.
//
// Book names and translation lists exactly as the scripture API reports them.
// Georgian, English and Russian are hand-maintained in \`languages.ts\`.

export const GENERATED_NAMES: Record<string, string[]> = {
${CODES.map(code => `  ${code}: ${list(loaded[code].names)},`).join('\n')}
};

export const GENERATED_VERSIONS: Record<string, string[]> = {
${CODES.map(code => `  ${code}: ${list(loaded[code].versions)},`).join('\n')}
};
`;

await writeFile(new URL('../src/lib/bible/languageData.generated.ts', import.meta.url), file);

CODES.forEach(code =>
  console.log(`${code}: ${loaded[code].names.length} names, ${loaded[code].versions.length} translations`),
);
